<a href="https://colab.research.google.com/github/chyijiunn/20201017/blob/main/20201031.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]])
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [5]:
ar2.shape

(2, 3)

In [7]:

ar2.ndim


2

In [8]:
f_ar = np.array([13,-3,8.88])
f_ar

array([13.  , -3.  ,  8.88])

In [9]:
f_ar.dtype

dtype('float64')

In [11]:
import numpy as np
np.ones((4, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [12]:
import numpy as np
np.arange(2, 3, 0.1) # start, end, step

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [13]:
import numpy as np
np.linspace(1., 4., 6) # start, end, num

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [14]:
import numpy as np
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [19]:
import numpy as np
#np.linspace(2.0, 3.0, num=5, endpoint=False)
np.linspace(2.0, 3.0, num=5, endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [20]:
import numpy as np
x = np.arange(2,10)
x

array([2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
import numpy as np
x = np.arange(2,10).reshape(2,4)
x

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [22]:
x = np.arange(2,10).reshape(4,2)
x

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
x = np.arange(2,10).reshape(3,4)
x

ValueError: ignored

In [24]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [25]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])